### ISSUE TITLE
Custom NUnit Test tags not supported.

### ISSUE THREAD

**Issue by kamilchodola** [AutomateThePlanet/Meissa#15]
Hello,

In Meissa project "Meissa.Plugins.NUnit" there is a method, which extract tests cases from library named "ExtractAllTestCasesFromTestLibrary". It extracts tests, which -> x.GetType().FullName.Equals(NunitTestAttributeName). In my tests project I have custom Test Tag named [CustomTest] and [CustomTestCase(string arg1, int arg2... etc)]. When i start runner, it extracts testsCases from library, and in my case it returns 0 cases. Temp file with TestsLists is empty. When i changed for a moment Tags from [CustomTest] to standard [Test] it works good.
Another question is related with [TestCase] tag. Is it supported in extracting cases from the library? Because there is a constant field with namespace only for Test tag, not for TestCase tag.

**Comment by angelovstanton** [comment]
You are right. This CustomTest attribute from your description it seems that it doesn't derive the the NUnit Test attribute? Otherwise, I guess it should worked?

About other attributes if there are part of NUnit, you can suggest what should be added and I will add them to the extractAll method so that they are supported.

For all custom made attributes, you can copy the NUnit plugin and create a custom plugin for your case. the DLL of the plugin should be placed in the Plugins folder and everything will work out-of-the-box.

**Comment by kamilchodola** [comment]
It's doesn't derive the NUnit Test attribute, but it derives a class NUnitAttribute and implements interfaces ISimpleTestBuilder, IApplyToTest, IImplyFixture, so exactly like NUnit original [Test] tag. I made it that way because I need to change the implementation of method ApplyToTest in NUnit, so I think it may be often a problem with it.

**Comment by angelovstanton** [comment]
It is strage then why .NET reflection doesn't catch them as well. Anyhow, if you list which attributes you want that point tests besides the custom ones I will add them to the plugin. 

For all custom ones, you will have to create a custom plugin, copy pasting the code and editing it. :)

**Comment by kamilchodola** [comment]
The only one I need to add is TestCase attribute :) It's a little different than a Test.
